"""PyTTa-based acoustic measurement engine.

Measurement flow:
    generate log sweep → play+record (PyTTa) → deconvolve (numpy FFT) → FR

PyTTa and numpy are imported lazily so the module loads in CI/test
environments without PortAudio.

The web API uses the split methods:
    generate_sweep() → play_signal() + compute_fr()
"""

from __future__ import annotations

import json
from dataclasses import dataclass, asdict
from datetime import datetime, timezone

from .config import Config


@dataclass
class FrequencyResponse:
    """Frequency response from a single log-sweep measurement."""

    frequencies: list[float]  # Hz, trimmed to calibration band
    spl: list[float]          # dBFS transfer-function magnitude
    sample_rate: int          # Hz
    sweep_duration: float     # seconds
    timestamp: str            # ISO-8601 UTC

    def to_json(self) -> str:
        return json.dumps(asdict(self))

    @classmethod
    def from_json(cls, s: str) -> "FrequencyResponse":
        return cls(**json.loads(s))

    @property
    def peak_spl(self) -> float:
        return max(self.spl)

    @property
    def freq_at_peak(self) -> float:
        idx = self.spl.index(self.peak_spl)
        return self.frequencies[idx]


class MeasurementEngine:
    """
    Runs a log-sweep measurement via PyTTa and returns a FrequencyResponse.

         generate log sweep  (pytta.generate.sweep)
                │
         play + record       (pytta.PlayRecMeasure)
                │
         deconvolve          H(f) = FFT(recording) / FFT(sweep)
                │
         trim to [freq_min, freq_max]
                │
         FrequencyResponse

    For the web API, the sweep can be split across requests:
        sweep_samples, sr, dur = engine.generate_sweep()
        engine.play_signal(sweep_samples, sr)    # non-blocking — 1s delay
        fr = engine.compute_fr(sweep_samples, recording_samples, sr=sr)
    """

    def __init__(self, config: Config) -> None:
        self.config = config

    # ── Public split API (used by web server) ─────────────────────────────

    def generate_sweep(
        self,
        freq_min: int | None = None,
        freq_max: int | None = None,
        duration: float | None = None,
        sample_rate: int | None = None,
    ) -> tuple[list[float], int, float]:
        """
        Generate a log-sweep signal using numpy (no pytta dependency).

        Returns (samples, sample_rate, duration) where samples is a flat list
        of float32 values suitable for playback or JSON serialisation.

        Raises RuntimeError if numpy is unavailable.
        """
        try:
            import numpy as np
        except ImportError as exc:
            raise RuntimeError("numpy is required — pip install numpy") from exc

        cfg = self.config.measurement
        f_min = freq_min if freq_min is not None else cfg.get("freq_min", 20)
        f_max = freq_max if freq_max is not None else cfg.get("freq_max", 200)
        dur = duration if duration is not None else cfg.get("sweep_duration", 3.0)
        sr = sample_rate if sample_rate is not None else cfg.get("sample_rate", 48000)

        # Logarithmic (exponential) sine sweep: y(t) = sin(2π·f_min·k·(e^(t/k) - 1))
        # where k = dur / ln(f_max / f_min)
        n = int(sr * dur)
        t = np.linspace(0.0, dur, n, endpoint=False)
        k = dur / np.log(f_max / f_min)
        phase = 2.0 * np.pi * f_min * k * (np.exp(t / k) - 1.0)
        samples: list[float] = np.sin(phase).astype(np.float32).tolist()
        return samples, sr, dur

    def play_signal(
        self,
        samples: list[float],
        sample_rate: int,
        out_channel: int | None = None,
    ) -> None:
        """
        Play samples through the configured output channel (blocking).

        Call this from a background thread to leave the web server responsive.
        """
        try:
            import numpy as np
            import sounddevice as sd
        except ImportError as exc:
            raise RuntimeError("sounddevice/numpy required for playback") from exc

        cfg = self.config.measurement
        ch = out_channel if out_channel is not None else cfg.get("output_channel", 1)
        arr = np.array(samples, dtype=np.float32).reshape(-1, 1)
        sd.play(arr, samplerate=sample_rate, device=None)
        sd.wait()

    def compute_fr(
        self,
        sweep_samples: list[float],
        recording_samples: list[float],
        freq_min: int | None = None,
        freq_max: int | None = None,
        sample_rate: int = 48000,
    ) -> FrequencyResponse:
        """
        Deconvolve sweep + browser recording into a FrequencyResponse.

        sweep_samples    — the sweep generated by generate_sweep()
        recording_samples — Float32 PCM captured by the browser
        sample_rate      — must match both arrays (browser records at this rate)
        """
        try:
            import numpy as np
        except ImportError as exc:
            raise RuntimeError("numpy is required — pip install numpy") from exc

        cfg = self.config.measurement
        f_min = freq_min if freq_min is not None else cfg.get("freq_min", 20)
        f_max = freq_max if freq_max is not None else cfg.get("freq_max", 200)
        dur = len(sweep_samples) / sample_rate

        frequencies, spl = self._compute_fr_arrays(
            np,
            np.array(sweep_samples, dtype=np.float64),
            np.array(recording_samples, dtype=np.float64),
            f_min,
            f_max,
            sample_rate,
        )
        return FrequencyResponse(
            frequencies=frequencies,
            spl=spl,
            sample_rate=sample_rate,
            sweep_duration=dur,
            timestamp=datetime.now(timezone.utc).isoformat(),
        )

    # ── Legacy full-cycle API (used by CLI measure command) ────────────────

    def measure(self) -> FrequencyResponse:
        """Run a full sweep measurement. Raises RuntimeError if dependencies unavailable."""
        try:
            import pytta
        except ImportError as exc:
            raise RuntimeError(
                "pytta is required for measurements — pip install pytta"
            ) from exc

        try:
            import numpy as np
        except ImportError as exc:
            raise RuntimeError(
                "numpy is required for measurements — pip install numpy"
            ) from exc

        cfg = self.config.measurement
        freq_min: int = cfg.get("freq_min", 20)
        freq_max: int = cfg.get("freq_max", 200)
        duration: float = cfg.get("sweep_duration", 3.0)
        sample_rate: int = cfg.get("sample_rate", 48000)
        in_channel: int = cfg.get("input_channel", 1)
        out_channel: int = cfg.get("output_channel", 1)

        sweep = pytta.generate.sweep(
            freq_min=freq_min,
            freq_max=freq_max,
            duration=duration,
            Fs=sample_rate,
            method="log",
        )

        meas = pytta.PlayRecMeasure(
            excitation=sweep,
            samplingRate=sample_rate,
            numInChannels=1,
            numOutChannels=1,
            inChannels=[in_channel],
            outChannels=[out_channel],
        )
        recording = meas.run()

        frequencies, spl = self._compute_fr(
            np, sweep, recording, freq_min, freq_max, sample_rate
        )

        return FrequencyResponse(
            frequencies=frequencies,
            spl=spl,
            sample_rate=sample_rate,
            sweep_duration=duration,
            timestamp=datetime.now(timezone.utc).isoformat(),
        )

    # ── Internals ─────────────────────────────────────────────────────────

    def _compute_fr_arrays(
        self,
        np,
        sweep_array,   # 1-D float64 ndarray
        rec_array,     # 1-D float64 ndarray
        freq_min: int,
        freq_max: int,
        sample_rate: int,
    ) -> tuple[list[float], list[float]]:
        """
        Core deconvolution on raw numpy arrays.

        H(f) = FFT(recording) / FFT(sweep)

        Arrays are zero-padded / truncated to the shorter length so they
        share the same FFT grid.
        """
        n = min(len(sweep_array), len(rec_array))
        X = np.fft.rfft(sweep_array[:n], n=n)
        Y = np.fft.rfft(rec_array[:n], n=n)

        with np.errstate(divide="ignore", invalid="ignore"):
            H = np.where(np.abs(X) > 1e-10, Y / X, 0.0 + 0.0j)

        freqs = np.fft.rfftfreq(n, d=1.0 / sample_rate)
        mag_db = 20.0 * np.log10(np.abs(H) + 1e-12)

        mask = (freqs >= freq_min) & (freqs <= freq_max)
        return freqs[mask].tolist(), mag_db[mask].tolist()

    def _compute_fr(
        self,
        np,
        sweep,       # PyTTa SignalObj
        recording,   # PyTTa SignalObj
        freq_min: int,
        freq_max: int,
        sample_rate: int,
    ) -> tuple[list[float], list[float]]:
        """Wrapper that extracts numpy arrays from PyTTa SignalObj inputs."""
        x = sweep.timeSignal[:, 0]
        y = recording.timeSignal[:, 0]
        return self._compute_fr_arrays(np, x, y, freq_min, freq_max, sample_rate)
